spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://postgres:5432/recommendations
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect