version: '3.8'

services:
  ml-service:
    image: pteroschin/ml-service:latest
    restart: always
    ports:
      - "8000:8000"

  producer-service:
    image: pteroschin/producer-service:latest
    restart: always
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - ml-service

  consumer-service:
    image: pteroschin/consumer-service:latest
    restart: always
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka
      - postgres

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_BROKER_ID=1
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: recommendations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 ml-service producer-service consumer-service
