global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'producer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['producer-service:8080']

  - job_name: 'consumer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['consumer-service:8080']

  - job_name: 'ml-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ml-service:8000']