global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'producer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['smart-product-recommender-producer-service-1:8091']

  - job_name: 'consumer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['smart-product-recommender-consumer-service-1:8090']

  - job_name: 'smart-product-recommender-ml-service-1'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ml-service:8000']