name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test-python:
    name: Test Python ML Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd ml-service
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd ml-service
          pytest

  build-push-java:
    name: Build & Push Java Services
    runs-on: ubuntu-latest
    needs: test-python

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & push producer-service
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/producer-service:latest -f producer-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/producer-service:latest

      - name: Build & push consumer-service
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/consumer-service:latest -f consumer-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/consumer-service:latest

      - name: Build & push ml-service
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ml-service:latest -f ml-service/Dockerfile ./ml-service
          docker push ${{ secrets.DOCKER_USERNAME }}/ml-service:latest
